version: 2
references:
  ## Workspace
  workspace: &workspace
               ~/circle102

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m

  ## Cache
  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle

  ## Android command
  download_dependencies: &download_dependencies
    run:
      name: Download Dependencies
      command: ./gradlew androidDependencies

jobs:
  test:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - *download_dependencies
      - *save_cache
      - run:
          name: Test
          command: ./gradlew lint testDevelopDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflow:
  version: 2
  my-workflow:
    jobs:
      - test